### ISSUE TITLE
need svd source for CRC unit to have workaround

### ISSUE THREAD

**Issue by pat-rogers** [AdaCore/Ada_Drivers_Library#163]
We lost the work-around for the compiler bug Q207-001 in stm32_svd-crc.ads, in which a register component has an extra "with Volatile" even though that is already specified at the record level.  I had manually added that to the Ada file but I don't know how to specify that in the SVD input part.

**Comment by Fabien-Chouteau** [comment]
This is tricky. Maybe you can comment the lines that generate STM32 SVD code in svd.mk, and with a comment explain that until the compiler is fixed we should be extra careful with STM32 SVDs.

**Comment by pat-rogers** [comment]
On 2/27/2017 1:06 PM, Fabien Chouteau wrote:
> This is tricky. Maybe you can comment the lines that generate STM32 SVD code in svd.mk, and with a comment explain that until the compiler is fixed we should be extra careful with STM32 SVDs.


Done but not yet checked in.

**Comment by Fabien-Chouteau** [comment]
@pat-rogers I think we can close this one, right?

**Comment by pat-rogers** [comment]
On 6/9/2017 11:44 AM, Fabien Chouteau wrote:
> @pat-rogers I think we can close this one, right?

Yes, thanks.
