### ISSUE TITLE
SDMMC_Interrupt_Handler interrupt priority

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#219]
In `STM32.SDMMC_Interrupt`, there is
```
   protected type SDMMC_Interrupt_Handler
     (Interrupt_ID : Ada.Interrupts.Interrupt_ID)
   is
      pragma Interrupt_Priority (250);
```

I found this because I was using a different RTS, with fewer priorities, but I think that either it should be in terms of `System.Interrupt_Priority'Last`, or left as a discriminant for the user to decide.

**Comment by Fabien-Chouteau** [comment]
@simonjwright you are right. I will add a discriminant.

**Comment by Fabien-Chouteau** [comment]
Done :) #264
