### ISSUE TITLE
hello teacher nice to meet you 

### ISSUE THREAD

**Issue by j1ng1992** [AdaCore/Ada_Drivers_Library#257]
i want to learn to how to use ada  in stm32 mcu ,and i see your document,,but i dont know how tu download your demo into the mcu, could you tell me how to do,teacher,and do you have Wechat or IG , i want to learn ada and if you have time i can ask you some question.

**Comment by Fabien-Chouteau** [comment]
Welcome to the Ada community :)

The procedure to load a executable on the board is described here: [examples/README.md](../tree/master/examples/README.md).

You can also what the demo videos on this blog post: https://blog.adacore.com/gps-for-bare-metal-development.

Regards,
