### ISSUE TITLE
Ethernet - Make with Ada

### ISSUE THREAD

**Issue by fustbariclation** [AdaCore/Ada_Drivers_Library#27]
I wanted to ask some questions, and chat about the Ethernet driver, in particular - I'm soon going to be working on the 'Make with Ada' competition ( http://www.makewithada.org ), and I want to get my hands on as much of the relevant documentation as possible.

I've ordered the STM32F746G-DISCO kit ( 32F746GDISCOVERY - http://www.mouser.com/ds/2/389/32f746gdiscovery-953766.pdf ) with the STM32F746NGH6 microcontroller. So it will be the stm32f7_discovery that I'll be specifically interested in - but I'm hoping that that will mainly be for the display, which is less important to my project than the ethernet port. [I may be interested in the USB port too, but as a connection to a second Ethernet device]

So I've put my questions into the Wiki here - hoping that they can turn into answers that'll be useful documentation for anybody else.

I'm hoping I've not done the wrong thing - but I'd love some feedback or suggestions from anybody here.

If anybody here is interested in what I'm trying to do, my project is a subset of the larger project that I've started to describe at the top level here:

[https://github.com/fustbariclation/Ada-Transport-Level-Security-TLS-module-](url)

**Comment by Fabien-Chouteau** [comment]
Hi Peter,

No the Ada_Drivers_Library wiki is not the right place to ask questions but thank you for starting the documentation effort. In my opinion it would be better to have documentation inside the repository (format to be discussed).

About your questions, we will not be able to answer everything. Please note that the stm32-eth package is experimental, you may have to redo some parts. Have a look at the STM32F7 documentation and also read the other drivers from this repository to see how they are implemented. In particular you will have to define the limit between what's specific to the STM32s and what can be shared with the other MCUs (HAL or components).

Note that we have a TCP/IP stack available as an example in the
SPARK GPL package (<INSTALL_DIR>/share/examples/spark/ipstack) on
libre.adacore.com. This may be a good place to start.

I'm closing this issue and I will also remove the wiki pages.

Thanks,


Regards,

**Comment by fustbariclation** [comment]
Thank you.

Regards,
Peter
