### ISSUE TITLE
Style check only on pull requests

### ISSUE THREAD

**Issue by Fabien-Chouteau** [AdaCore/Ada_Drivers_Library#271]
Björn made a good comment on [comp.lang.ada](https://groups.google.com/forum/#!topic/comp.lang.ada/OidrH33UBJg) that enforcing the coding style with error message (`-gnaty -gnatwe`) is not friendly for beginners starting to use the library.

In the end we only want to enforce the coding style on code that is checked-in. So there might be a way to only enable style check for pull requests validation.

**Comment by yannickmoy** [comment]
why? This only applies to the library itself, not the user code.

**Comment by Fabien-Chouteau** [comment]
It also applies to the examples that users will start from.
