### ISSUE TITLE
How to add support for new devices?

### ISSUE THREAD

**Issue by gamnes** [AdaCore/Ada_Drivers_Library#275]
Is there a step by step guide on how to add support for another architecture/board - say for example the Nordic Semiconductor nRF52832-DK?

How does a user of this library make his own project for his custom board that uses one of the supported architectures?

**Comment by Fabien-Chouteau** [comment]
Hi @gamnes,

> Is there a step by step guide on how to add support for another architecture/board - say for example the Nordic Semiconductor nRF52832-DK?
> 

We do not have such guide for the moment, but here are two documents that can help you understanding the library:
 - [A design overview](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/docs/design.md) which gives you a high level view of how the library is organized
 - [Ada_Drivers_Library vs bb-runtimes](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/docs/Ada_Drivers_Library-vs-bb_runtimes.md) which defines a line between what should be in the run-time and what should be in `Ada Drivers Library`

For the nRF52, correct me if I'm wrong but I think that all the variants share the same core and peripherals, only the size of RAM and flash are different. If that's the case, here is the directories that you will have to create and what you should put inside:
 - `arch/ARM/Nordic/nRF52/` Root directory of the nRF52 support
 - `arch/ARM/Nordic/nRF52/svd` Directory containing the Ada specifications generated from the SVD hardware description. You have to use the [svd2ada](https://github.com/AdaCore/svd2ada) tool for that. You should edit the `arch/svd.mk` Makefile to add the nRF52 SVD.
 - `arch/ARM/Nordic/nRF52/drivers/`: driver implementation. As much as possible the drivers should implement the interfaces defined in `hal/src`. You can look at the equivalent for the nRF51 or the STM32s.
 - `arch/ARM/Nordic/nRF52/devices/`: This directory should contain a `nRF52.Device` package that declare the instances of peripherals (GPIO points, I2C, etc.). You can look at the equivalent for the nRF51 or the STM32s.

We will also ask that you provide an example for a board that uses the nRF52. I think the dev kit is the best option here. That board support will go into `boards/nRF52_devkit` directory. It doesn't have to cover all the features of the board, a blinky example is good enough.

The last modification will be to add information about the device and the board in the [project_wizard and config scripts](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/scripts/config/devices.py).

That is quite a lot of info, but remember that it can be done step by step and that we are here to help. So don't hesitate to ask questions or show us your progress.

> How does a user of this library make his own project for his custom board that uses one of the supported architectures?

There are two ways:
 - The easy/beginner way is to start from one of the examples and modify it
 - The more correct way is to use the [project_wizard](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/docs/how_to_create_my_own_adl_project.md#project-wizard)

Best regards,
