### ISSUE TITLE
Contributions to components

### ISSUE THREAD

**Issue by sai-y** [AdaCore/Ada_Drivers_Library#282]
Hello, 

I was reading through the repo's README and there was a mention about contributing to components. What does components mean? 

Are you looking for individual contributions towards sensors, motor drivers etc? If so, I am interested in making contributions.

**Comment by Fabien-Chouteau** [comment]
Hi @sai-y 

> I was reading through the repo's README and there was a mention about contributing to components. What does components mean?

The `components` layer is mentioned at the end of the [design document](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/docs/design.md).

> Are you looking for individual contributions towards sensors, motor drivers etc? If so, I am interested in making contributions.

Yes! :) 

Let us know if you need help.

You can start by looking at what is already available: https://github.com/AdaCore/Ada_Drivers_Library/tree/master/components/src

Best regards,
