### ISSUE TITLE
Example: tracks_display.adb incorrect definition

### ISSUE THREAD

**Issue by fustbariclation** [AdaCore/Ada_Drivers_Library#29]
tracks_display.adb:37:04: "Track_Color" conflicts with declaration at line 36

The problem is:

  Track_Color      : constant Bitmap_Color := HAL.Bitmap.Light_Gray;

The package wants gray misspelt 'Grey'. Replacing line 36 with:

   Track_Color      : constant Bitmap_Color := HAL.Bitmap.Light_Grey;

Fixes the problem.

**Comment by lambourg** [comment]
The commit https://github.com/AdaCore/Ada_Drivers_Library/commit/b441094a7c4869a8e5bf364dc54b7ea36a6bd6fe already fixes this issue. So normally, updating your repository should make the example build properly.

Best regards,
- Jerome
