### ISSUE TITLE
STM32F42x needs UART 7, 8

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#31]
ARM/STM32/devices/stm32f42x/stm32-device.ads should support UART7, UART8 (RM0090 Fig 27 shows they are on STM32F42xxx and STM32F43xxx).

Also the AFs ...

**Comment by lambourg** [comment]
Hi Simon,

As we're currently working on other parts of the drivers library, feel free to contribute patches to enhance the library. We're very open to contributions here... And the more contributions, the better. Moreover, adding drivers we're not actually testing is of very low interest, so if you have a situation where UART7/8 are needed, it's better if you add the proper driver to those peripherals.

Best regards,
- Jerome

**Comment by lambourg** [comment]
Ok, this is now fixed!

As always, thanks for your report, Simon.

**Comment by simonjwright** [comment]
Thanks, Jerome!
