### ISSUE TITLE
Using STM32.SPI

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#339]
STM32.SPI starts with
```
package STM32.SPI is

   type Internal_SPI_Port is private;

   type SPI_Port (Periph : not null access Internal_SPI_Port) is
      limited new HAL.SPI.SPI_Port with private;
```
and I’m puzzled about how this is to be used given that we know nothing about `Internal_SPI_Port`.

I’ve got as far as
```
   Peripheral : aliased STM32.SPI.Internal_SPI_Port;
   SPI_Port : STM32.SPI.SPI_Port (Peripheral'Access);
```
which doesn’t seem to be much use. 

Somehow I need to use the full declaration
```
   type Internal_SPI_Port is new STM32_SVD.SPI.SPI_Peripheral;
```
so that maybe I could say
```
   SPI_Port : STM32.SPI.SPI_Port (STM32_SVD.SPI.SPI1_Periph'Access);
```

**Comment by Fabien-Chouteau** [comment]
Hi @simonjwright,

Peripherals instances are already declared for you in [`STM32.Device`](https://github.com/AdaCore/Ada_Drivers_Library/blob/master/arch/ARM/STM32/devices/stm32f40x/stm32-device.ads#L363). With the correct address and number of instances in the device.

You can see an example of SPI initialization [here](https://github.com/AdaCore/Ada_Drivers_Library/blob/5ffdf12bec720aea12467229bb5862c465bf0333/boards/OpenMV2/src/openmv.adb#L140).
