### ISSUE TITLE
Proposed PWM3901 driver

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#343]
The Crazyflie Flow Deck uses a PWM3901 optical flow sensor, I propose to make a driver for it (under `components/src/motion`, I think?).

The chip uses SPI; in Crazyflie, only decks use SPI (decks are like shields). I’d like to add `Initialize_Deck_SPI`to `boards/crazyflie/src/stm32-board.ad?` on the lines of `Initialize_Shield_SPI` in the equivalent OpenMV package.

Would these proposals be acceptable?

(the license in my source material is [MIT](https://github.com/pimoroni/pmw3901-python/blob/master/library/LICENSE.txt))

**Comment by Fabien-Chouteau** [comment]
> Would these proposals be acceptable?

Absolutely Simon :)

As you said there is already something similar for the OpenMV2.

> (the license in my source material is [MIT](https://github.com/pimoroni/pmw3901-python/blob/master/library/LICENSE.txt))

Since you are going to write your own drivers, that is not going to be a problem.

Looking forward to this new driver, and to see it in action on the Crazyflie :)
