### ISSUE TITLE
Access to FE310-specific performance counters

### ISSUE THREAD

**Issue by rod-chapman** [AdaCore/Ada_Drivers_Library#365]
Following PR #362, we can now implement support for the micro-architectural performance counters implemented by the FE310 in the HiFive1. Only 2 such counters are implemented (mhpmcounter3 and 4), controlled by mhpmevent3 and 4 control registers, with specific meaning defined bu the FE310 Reference Manual.

**Comment by rod-chapman** [comment]
Actually, the counters are specific to the FE31 RISC-V core, which is in the FE310-G000, FE310-G002 and FE310-G003 variants, so is common to all, so these can apply to both the HiFive1 and the HiFive1_RevB boards.

So... suggest that the counters are defined in a new public child package of FE310 - perhaps FE310.Perf ???

**Comment by Fabien-Chouteau** [comment]
Hi Rod,

I prefer `FE310.Performance_Monitor` based on the documentation chapter name.

**Comment by rod-chapman** [comment]
FE310.Performance_Monitor is good for me! Do you feel you can adapt the package spec that I sent you, or would you prefer to start from scratch?

**Comment by Fabien-Chouteau** [comment]
> Do you feel you can adapt the package spec that I sent you, or would you prefer to start from scratch?

I thought you were going to do it :)

**Comment by rod-chapman** [comment]
OK... I will have a go today. Is there a documented coding standard and dev process that I'm supposed to follow?

**Comment by rod-chapman** [comment]
Hmmm...
```
RodPro2:drivers rchapman$ git push --set-upstream origin fe310_performance
remote: Permission to AdaCore/Ada_Drivers_Library.git denied to rod-chapman.
fatal: unable to access 'https://github.com/AdaCore/Ada_Drivers_Library.git/': The requested URL returned error: 403
```

Fabien - do you need to grant me permission to push?

**Comment by rod-chapman** [comment]
I also sent the CLA (a PDF scan) to contributions@adacore.com

**Comment by rod-chapman** [comment]
OK.. PR 370 is open. A first draft is there. I am trying to test it now...
