### ISSUE TITLE
Make HAL packages preelaborable

### ISSUE THREAD

**Issue by JeremyGrosser** [AdaCore/Ada_Drivers_Library#399]
I'd like to add `pragma Preelaborate` to a few packages in rp2040_hal, but I can't do this as long as there's a dependency on the HAL packages, which are not preelaborated. Could we add Preelaborate to the HAL packages in ADL?

**Comment by Fabien-Chouteau** [comment]
They should all be "preelaborable". You can try to submit a patch and we'll see if the builds pass.
