### ISSUE TITLE
Support for STM32F411CEU6 board

### ISSUE THREAD

**Issue by mcxbain** [AdaCore/Ada_Drivers_Library#419]
will STM32F411CEU6 be supported?
https://stm32-base.org/boards/STM32F411CEU6-WeAct-Black-Pill-V2.0

**Comment by Fabien-Chouteau** [comment]
Hello @mcxbain, the chip is an STM32F411 so it should be mostly compatible with the STM32F407 discovery.
But the run-time and ADL configuration has to be tweaked, so not an out-of-the-box solution.
