### ISSUE TITLE
No repository for HAL crate available.

### ISSUE THREAD

**Issue by Joebeazelman** [AdaCore/Ada_Drivers_Library#434]
I'd like to pin and modify one of my dependency crates, HAL, but it doesn't exist as a separate repository. According to the crates' description it's only a "snapshot" this repository, specifically the HAL subfolder.

I went through some effort to extract the HAL directory and convert it into a submodule, but it can't be built since it doesn't contain a project file. Where does this snapshot live?

**Comment by Fabien-Chouteau** [comment]
Hello @Joebeazelman, for the moment it is hosted here: https://github.com/Fabien-Chouteau/hal
