### ISSUE TITLE
Dependencies/versions of several crates don't match anymore

### ISSUE THREAD

**Issue by ThyMYthOS** [AdaCore/Ada_Drivers_Library#435]
@Fabien-Chouteau @JeremyGrosser 

- [cortex_m](https://alire.ada.dev/crates/cortex_m) 0.5.0 depends on hal ~0.3
- [usb_embedded](https://alire.ada.dev/crates/usb_embedded) 0.3.1 depends on hal ~0.4
- [rp2040_hal](https://alire.ada.dev/crates/rp2040_hal) 2.3.0 depends on cortex_m 0.5.0 and hal ~0.3
- [stm32f0x2_hal](https://alire.ada.dev/crates/stm32f0x2_hal) 0.3.0 depends on cortex_m 0.5.0 and hal ~0.3

So in order to update `rp2040_hal` and/or `stm32f0x2_hal` to `usb_embedded 0.3.1`, `cortex_m` has to be updated to depend on `hal ~0.4`.

**Comment by Fabien-Chouteau** [comment]
Hi @ThyMYthOS I forgot to mention that we published 1.0.0 released of `hal`, `cortex_m`, `usb_embedded`, `atomic`, and `bbqueue`.

But it looks like you already have the news.
