### ISSUE TITLE
Serial port example build fails

### ISSUE THREAD

**Issue by NitinBhaskar** [AdaCore/Ada_Drivers_Library#54]
Serial port example build fails due to "Ada.Streams" is not a predefined library unit.

**Comment by Fabien-Chouteau** [comment]
Hi,

Please try to change the RTS scenario variable to ravenscar-full in the "Scenario" window of GPS.

Regards,

**Comment by NitinBhaskar** [comment]
Hi,

Thanks for the solution.

Regards,
