### ISSUE TITLE
AK8963 scalings should use individual components

### ISSUE THREAD

**Issue by simonjwright** [AdaCore/Ada_Drivers_Library#59]
In components/src/motion/ak8963/ak8963.adb, procedure Get_Heading, it says

         if Status = Ok then
            Mx := Mx * ((Float (Buffer (1)) - 128.0) / 256.0 + 1.0);
            My := My * ((Float (Buffer (1)) - 128.0) / 256.0 + 1.0);
            Mz := Mz * ((Float (Buffer (1)) - 128.0) / 256.0 + 1.0);
         end if;

The Y component should use Buffer (2), the Z component should use Buffer (3).

**Comment by lambourg** [comment]
Thanks Simon, this is now fixed.
